# Generated by Django 5.1.6 on 2025-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('academic', 'Acadêmico'), ('personal', 'Pessoal'), ('professional', 'Profissional')], default='personal', max_length=20, verbose_name='Tipo'),
        ),
    ]
