# Generated by Django 5.1.6 on 2025-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(default='', verbose_name='Conteúdo Completo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('academic', 'Acadêmico'), ('personal', 'Pessoal'), ('professional', 'Profissional')], default='personal', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', max_length=200, verbose_name='Breve Descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluído')], default='in_progress', max_length=50, verbose_name='Status'),
        ),
    ]
