# Generated by Django 5.1.6 on 2025-03-09 22:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tag_options_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top3Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text="Font Awesome icon class (e.g., 'fas fa-paw me-2')", max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('item1_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('item1_name', models.CharField(max_length=100)),
                ('item1_link', models.URLField(blank=True, null=True)),
                ('item2_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('item2_name', models.CharField(max_length=100)),
                ('item2_link', models.URLField(blank=True, null=True)),
                ('item3_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('item3_name', models.CharField(max_length=100)),
                ('item3_link', models.URLField(blank=True, null=True)),
                ('fun_comment', models.TextField(help_text='A fun comment about the TOP 3 items')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TOP 3 Card',
                'verbose_name_plural': 'TOP 3 Cards',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='in_progress', max_length=50, verbose_name='Status'),
        ),
    ]
