# Generated by Django 5.1.6 on 2025-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_visitor_alter_top3card_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='in_progress', max_length=50, verbose_name='Status'),
        ),
    ]
