# Generated by Django 5.1.6 on 2025-03-10 11:15

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('short_description', models.CharField(default='', max_length=200, verbose_name='Breve Descrição')),
                ('content', models.TextField(default='', verbose_name='Conteúdo Completo')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='in_progress', max_length=50, verbose_name='Status')),
                ('project_type', models.CharField(choices=[('academic', 'Acadêmico'), ('personal', 'Pessoal'), ('professional', 'Profissional')], default='personal', max_length=50, verbose_name='Tipo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link do Projeto')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Link do GitHub')),
                ('featured', models.BooleanField(default=False, verbose_name='Projeto Destacado')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='main.project')),
            ],
            options={
                'verbose_name': 'Rascunho de Projeto',
                'verbose_name_plural': 'Rascunhos de Projetos',
            },
        ),
    ]
